name: docs-alexdoesvoices-com

services:
  docs:
    build: .
    restart: always
    environment:
      - PORT=7090
      - HOST=0.0.0.0
    ports:
      - "7090:7090" # Or keep it internal and use Caddy to proxy it